project_id = "xmmfafefyfqzmsutqwug"

[functions.sync-youtube-playlist]
verify_jwt = false

[functions.create-holiday-sprint-payment]
verify_jwt = false

[functions.send-holiday-sprint-confirmation]
verify_jwt = false

[functions.send-intake-confirmation]
verify_jwt = false

[functions.create-video-reel-payment]
verify_jwt = false

[functions.create-ssf-payment]
verify_jwt = false

[functions.send-ssf-invoice]
verify_jwt = false

[functions.create-tiktok-live-payment]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false
